version: '3'

services:
  vl_backend:
    image: docker.pkg.github.com/ai-poli-bllf/backend/vl_backend:0.0.2
    container_name: vl_backend
    restart: unless-stopped
    networks:
      - virtual_labs
    depends_on:
      - "vl_db"
    ports:
      - 8080:8080

  vl_db:
    image: mariadb
    container_name: vl_db
    restart: unless-stopped
    networks:
      - virtual_labs
    volumes:
      #      da cambiare prima dell'uso
      - /home/stefano/IdeaProjects/Backend/db_data/:/var/lib/mysql
    #    ports:
    #      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=ciao123
      - MYSQL_DATABASE=teams

networks:
  virtual_labs:
    external: false
