version: '3'

services:
  vl_frontend:
    image: docker.pkg.github.com/ai-poli-bllf/frontend/vl_frontend:latest
    container_name: vl_frontend
    restart: unless-stopped
    networks:
      - virtual_labs
    ports:
      - 4200:4200

  vl_backend:
    image: docker.pkg.github.com/ai-poli-bllf/backend/vl_backend:latest
    container_name: vl_backend
    restart: unless-stopped
    networks:
      - virtual_labs
    depends_on:
      - "vl_db"
    ports:
      - 8080:8080

  vl_db:
    image: mariadb
    container_name: vl_db
    restart: unless-stopped
    networks:
      - virtual_labs
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ciao123
      - MYSQL_DATABASE=teams
volumes:
  db_data:

networks:
  virtual_labs:
    external: false
